print("------------------------------------------------------------------------")
print("BIODATA")
print("------------------------------------------------------------------------")

a = str("Rahmat Herpradipto")
b = str("I0320083")
c = str("B")
d = str("S1-Teknik Industri")
e = str("Teknik")
f = str("Universitas Sebelas Maret")
g = str("Jl. Jonggrang 1 No.18 Kota Madiun")
h = str("Madiun, 10 Februari 2002")
i = str("laki-laki")
j = int("18")
k = int("177")
l = int("70")
m = int("43")

print("data yang harus diisi")
print("1. Nama :", a)
print("2. NIM :", b)
print("3. Kelas :", c)
print("4. Program Studi :", d)
print("5. Fakultas :", e)
print("6. Universitas :", f)
print("7. Alamat :", g)
print("8. Tempat, Tanggal Lahir :", h)
print("9. Jenis Kelamin :", i)
print("10. Umur :", j)
print("11. Tinggi Badan :", k)
print("12. Berat Badan :", l)
print("13. Ukuran Sepatu :", m)

print("------------------------------------------------------------------------")
print("------------------------------------------------------------------------")